/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "surface-variant": "#2f3635",
          "surface-container-low": "#161d1c",
          "surface-container-highest": "#2f3635",
          "primary": "#62f3ec",
          "on-secondary-fixed": "#151c24",
          "surface": "#0e1514",
          "surface-dim": "#0e1514",
          "inverse-surface": "#dde4e2",
          "surface-container-lowest": "#090f0f",
          "primary-fixed": "#68f8f1",
          "secondary-container": "#434a53",
          "outline-variant": "#3c4948",
          "inverse-primary": "#006a67",
          "secondary-fixed": "#dce3ee",
          "surface-tint": "#44dbd5",
          "error-container": "#93000a",
          "on-primary-fixed": "#00201f",
          "background": "#0e1514",
          "tertiary-container": "#ffb254",
          "surface-bright": "#343a3a",
          "on-tertiary-fixed-variant": "#673d00",
          "tertiary": "#ffd7ad",
          "on-surface": "#dde4e2",
          "secondary": "#c0c7d2",
          "on-tertiary": "#482900",
          "primary-fixed-dim": "#44dbd5",
          "on-secondary": "#2a313a",
          "tertiary-fixed-dim": "#ffb865",
          "on-tertiary-container": "#724500",
          "primary-container": "#3dd6d0",
          "on-secondary-fixed-variant": "#404750",
          "on-error": "#690005",
          "error": "#ffb4ab",
          "secondary-fixed-dim": "#c0c7d2",
          "on-background": "#dde4e2",
          "outline": "#859492",
          "tertiary-fixed": "#ffddba",
          "on-secondary-container": "#b2b9c4",
          "on-primary": "#003735",
          "surface-container": "#1a2120",
          "on-primary-fixed-variant": "#00504d",
          "inverse-on-surface": "#2b3231",
          "surface-container-high": "#252b2b",
          "on-tertiary-fixed": "#2b1700",
          "on-surface-variant": "#bbc9c8",
          "on-primary-container": "#005956",
          "on-error-container": "#ffdad6"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      "spacing": {
          "unit": "4px",
          "gutter": "16px",
          "topbar-height": "64px",
          "container-margin": "24px",
          "sidebar-width": "260px"
      },
      "fontFamily": {
          "kpi-value": ["Inter"],
          "body-md": ["Inter"],
          "display-lg": ["Space Grotesk"],
          "headline-sm": ["Space Grotesk"],
          "headline-md": ["Space Grotesk"],
          "body-lg": ["Inter"],
          "headline-lg": ["Space Grotesk"],
          "label-caps": ["Inter"]
      },
      "fontSize": {
          "kpi-value": ["28px", {"lineHeight": "32px", "fontWeight": "600"}],
          "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
          "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
          "headline-sm": ["18px", {"lineHeight": "24px", "letterSpacing": "0.02em", "fontWeight": "600"}],
          "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "500"}],
          "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
          "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "500"}],
          "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
